In [4]:
import numpy as np
import re

In [6]:
def cos_distance(x,y):

    c = x@y
    x = np.sqrt(x@x)
    y = np.sqrt(y@y)
    c = 1 - c/(x*y)
    return c


In [7]:
f = open(r'C:\Users\Пользователь\Desktop\HW1\sentences.txt','r')


In [8]:
lines = f.readlines()
lines

['In comparison to dogs, cats have not undergone major changes during the domestication process.\n',
 'As cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.\n',
 'A common interactive use of cat for a single file is to output the content of a file to standard output.\n',
 'Cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.\n',
 'In one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.\n',
 'The domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.\n',
 'Domestic cats are similar in size to the other members of the genus Felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).\n',
 'However, if the output is piped or redirected, cat is unnecessary.\n',
 'cat with one named file is safer whe

In [9]:
matrices = []

for line in lines:

    a = [string for string in re.split('[^a-z]',line.lower()) if string != '']
    matrices.append(a)
matrices

[['in',
  'comparison',
  'to',
  'dogs',
  'cats',
  'have',
  'not',
  'undergone',
  'major',
  'changes',
  'during',
  'the',
  'domestication',
  'process'],
 ['as',
  'cat',
  'simply',
  'catenates',
  'streams',
  'of',
  'bytes',
  'it',
  'can',
  'be',
  'also',
  'used',
  'to',
  'concatenate',
  'binary',
  'files',
  'where',
  'it',
  'will',
  'just',
  'concatenate',
  'sequence',
  'of',
  'bytes'],
 ['a',
  'common',
  'interactive',
  'use',
  'of',
  'cat',
  'for',
  'a',
  'single',
  'file',
  'is',
  'to',
  'output',
  'the',
  'content',
  'of',
  'a',
  'file',
  'to',
  'standard',
  'output'],
 ['cats',
  'can',
  'hear',
  'sounds',
  'too',
  'faint',
  'or',
  'too',
  'high',
  'in',
  'frequency',
  'for',
  'human',
  'ears',
  'such',
  'as',
  'those',
  'made',
  'by',
  'mice',
  'and',
  'other',
  'small',
  'animals'],
 ['in',
  'one',
  'people',
  'deliberately',
  'tamed',
  'cats',
  'in',
  'a',
  'process',
  'of',
  'artificial',
  's

In [10]:
all_words = list(set([word for sentence in matrices for word in sentence]))
words_index = {word : i for i, word in enumerate(all_words)}
words_index

{'t': 0,
 'on': 1,
 'by': 2,
 'sounds': 3,
 'three': 4,
 'arguments': 5,
 'place': 6,
 'x': 7,
 'basic': 8,
 'from': 9,
 'often': 10,
 'apple': 11,
 'animals': 12,
 'firmware': 13,
 'allow': 14,
 'to': 15,
 'later': 16,
 'cat': 17,
 'similar': 18,
 'some': 19,
 'mid': 20,
 'simply': 21,
 'roughly': 22,
 'command': 23,
 'catenates': 24,
 'artificial': 25,
 'through': 26,
 'installed': 27,
 'fifth': 28,
 'based': 29,
 'that': 30,
 'yosemite': 31,
 'piped': 32,
 'genus': 33,
 'off': 34,
 'enhancements': 35,
 'receives': 36,
 'no': 37,
 'stdout': 38,
 'moved': 39,
 'the': 40,
 'or': 41,
 'they': 42,
 'marks': 43,
 'not': 44,
 'a': 45,
 'part': 46,
 'process': 47,
 'computers': 48,
 'however': 49,
 'single': 50,
 'dogs': 51,
 'organisms': 52,
 'longer': 53,
 'high': 54,
 'ancestor': 55,
 'their': 56,
 'members': 57,
 'will': 58,
 'where': 59,
 'useful': 60,
 'learned': 61,
 'file': 62,
 'predecessor': 63,
 'count': 64,
 'just': 65,
 'running': 66,
 'two': 67,
 'wild': 68,
 'are': 69,
 'weig

In [12]:
final_matrix = np.zeros((len(lines),len(words_index)))

for i,sentence in enumerate(matrices):
    for word in sentence:
        final_matrix[i,words_index[word]] = sentence.count(word)
final_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [13]:
distances = np.array([cos_distance(final_matrix[0], final_matrix[i]) for i in range(1, final_matrix.shape[0])])
distances

array([0.95275444, 0.86447381, 0.89517152, 0.77708871, 0.94023857,
       0.73273876, 0.92587507, 0.88427249, 0.90550888, 0.83281654,
       0.88047714, 0.83964325, 0.87035926, 0.87401184, 0.94427218,
       0.84063619, 0.9566445 , 0.94427218, 0.88854436, 0.84275727,
       0.82503645])

In [14]:
near_sentence = np.argsort(distances)[:2] + 1
near_sentence

array([6, 4], dtype=int64)